import type { Metadata } from "next";
import { Nav } from "@/components/landing/Nav";
import { Footer } from "@/components/landing/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — SelfForge",
};

const EFFECTIVE_DATE = "July 27, 2026";
const CONTACT_EMAIL = "matthew.duchatellier@gmail.com";

export default function TermsPage() {
  return (
    <div className="flex flex-1 flex-col">
      <Nav />
      <main className="flex flex-1 flex-col bg-white pt-32 pb-24">
        <div className="mx-auto w-full max-w-3xl px-5 sm:px-8">
          <h1 className="font-display text-3xl tracking-tight text-ink-950 sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-ink-500">Effective {EFFECTIVE_DATE}</p>

          <div className="mt-10 space-y-8 text-ink-700 [&_h2]:mt-2 [&_h2]:font-display [&_h2]:text-xl [&_h2]:text-ink-950 [&_p]:leading-relaxed [&_ul]:list-disc [&_ul]:space-y-2 [&_ul]:pl-6 [&_li]:leading-relaxed">
            <section>
              <h2>1. Agreement to Terms</h2>
              <p>
                These Terms of Service (&quot;Terms&quot;) govern your access to and use of
                SelfForge (&quot;SelfForge,&quot; &quot;we,&quot; &quot;us,&quot; or
                &quot;our&quot;), including our website, web application, and mobile
                application (together, the &quot;Service&quot;). By creating an account or
                otherwise using the Service, you agree to be bound by these Terms and by our{" "}
                <a href="/privacy" className="underline hover:text-ink-950">
                  Privacy Policy
                </a>
                . If you do not agree, do not use the Service.
              </p>
            </section>

            <section>
              <h2>2. Eligibility</h2>
              <p>
                You must be at least 18 years old to create an account, purchase a
                subscription, or otherwise use the Service. By using the Service, you
                represent that you meet this requirement.
              </p>
            </section>

            <section>
              <h2>3. Description of Service</h2>
              <p>
                SelfForge provides AI-generated self-improvement guidance covering areas
                such as fitness, nutrition, skincare, style, and discipline, along with
                habit tracking, progress tracking, and an AI chat coach. Content is
                generated by a third-party AI model based on information you provide.
              </p>
            </section>

            <section>
              <h2>4. Not Medical, Health, or Professional Advice</h2>
              <p>
                SelfForge is not a medical device and does not provide medical, mental
                health, nutritional, or other licensed professional advice. AI-generated
                content is for general informational and motivational purposes only and is
                not a substitute for consultation with a qualified physician, dietitian,
                therapist, or other professional. Always seek the advice of a qualified
                professional before making changes to your diet, exercise routine, or
                health regimen, particularly if you have an existing medical condition.
              </p>
            </section>

            <section>
              <h2>5. Accounts</h2>
              <p>
                You are responsible for maintaining the confidentiality of your account
                credentials and for all activity that occurs under your account. You agree
                to provide accurate information and to keep it up to date.
              </p>
            </section>

            <section>
              <h2>6. Subscriptions, Billing, and Cancellation</h2>
              <p>
                Certain features require a paid subscription, billed in advance on a
                recurring basis through our payment processor, Stripe. By subscribing, you
                authorize us to charge your payment method on each renewal until you
                cancel. You may cancel at any time through the billing portal available in
                your account settings; cancellation takes effect at the end of the current
                billing period, and we do not provide refunds or credits for partial
                billing periods except where required by law.
              </p>
            </section>

            <section>
              <h2>7. Acceptable Use</h2>
              <p>You agree not to:</p>
              <ul>
                <li>Use the Service for any unlawful purpose or in violation of these Terms;</li>
                <li>Attempt to circumvent rate limits, usage restrictions, or paywalls;</li>
                <li>
                  Reverse engineer, scrape, or use automated means to access the Service
                  beyond normal use;
                </li>
                <li>Interfere with or disrupt the integrity or performance of the Service.</li>
              </ul>
            </section>

            <section>
              <h2>8. Termination</h2>
              <p>
                We may suspend or terminate your access to the Service at any time if we
                reasonably believe you have violated these Terms. You may stop using the
                Service and delete your account at any time.
              </p>
            </section>

            <section>
              <h2>9. Disclaimers</h2>
              <p>
                The Service is provided &quot;as is&quot; and &quot;as available&quot;
                without warranties of any kind, whether express or implied, including
                warranties of merchantability, fitness for a particular purpose, and
                non-infringement. We do not warrant that the Service will be uninterrupted,
                error-free, or that AI-generated content will be accurate or suitable for
                your circumstances.
              </p>
            </section>

            <section>
              <h2>10. Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, SelfForge and its operators will
                not be liable for any indirect, incidental, special, consequential, or
                punitive damages, or any loss of data, arising out of or related to your
                use of the Service. Our total liability for any claim relating to the
                Service will not exceed the amount you paid us in the twelve months before
                the claim arose.
              </p>
            </section>

            <section>
              <h2>11. Changes to These Terms</h2>
              <p>
                We may update these Terms from time to time. If we make material changes,
                we will provide reasonable notice, such as by posting an updated version on
                this page with a new effective date. Continued use of the Service after
                changes take effect constitutes acceptance of the revised Terms.
              </p>
            </section>

            <section>
              <h2>12. Governing Law</h2>
              <p>
                These Terms are governed by the laws of the United States, without regard
                to conflict-of-laws principles.
              </p>
            </section>

            <section>
              <h2>13. Contact</h2>
              <p>
                Questions about these Terms can be sent to{" "}
                <a href={`mailto:${CONTACT_EMAIL}`} className="underline hover:text-ink-950">
                  {CONTACT_EMAIL}
                </a>
                .
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
